name: cuidapet_api
description: An empty Aqueduct application.
version: 0.0.1


environment:
  sdk: ">=2.7.0 <3.0.0"



dependencies:
  aqueduct: 3.3.0+1
  mysql1: ^0.17.1
  jaguar_jwt: ^2.1.6
  dio: ^3.0.9

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0