name: cuidapet_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_mobx: ^2.0.6+5
  asuka: ^2.0.1+3
  flutter_modular: ^5.0.3
  flutter_screenutil: ^5.6.0
  mobx: ^2.1.3
  dio: ^4.0.6
  
  flutter_dotenv: ^5.0.2
  logger: ^1.1.0

  flutter_secure_storage: ^7.0.1
  shared_preferences: ^2.0.15
  
  ##Firebase
  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0
  ##firebase_auth: ^4.2.5
  firebase_remote_config: ^3.0.9
  ##firebase_messaging: ^14.2.1
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  mobx_codegen: ^2.1.1


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf