name: cuidapet_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  asuka: ^2.0.1+3
  dio: ^4.0.6
  flutter_mobx: ^2.0.6+5
  flutter_modular: ^5.0.3
  flutter_screenutil: ^5.6.0
  mobx: ^2.1.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  mobx_codegen: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

