name: cuidapet_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  asuka: ^2.1.0
  flutter_modular: ^5.0.3
  flutter_mobx: ^2.0.6+5
  mobx: ^2.2.1
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter_typeahead: ^4.8.0
  validatorless: ^1.2.3
  json_annotation: ^4.8.1
  flutter_screenutil: ^5.9.0
  sqflite: ^2.3.0
  synchronized: ^3.1.0
  path: ^1.8.3
  nil: ^1.1.1
  
  intl: ^0.18.1
  url_launcher: ^6.1.12

  flutter_dotenv: ^5.1.0
  logger: ^1.4.0


  flutter_secure_storage: ^8.1.0
  shared_preferences: ^2.2.2

    
  ##Firebase
  firebase_core: ^2.21.0
  firebase_analytics: ^10.6.3
  firebase_auth: ^4.12.1
  firebase_remote_config: ^4.3.3
  firebase_messaging: ^14.7.3
  google_sign_in: ^6.1.5  
  google_maps_flutter: ^2.5.0
  ##google_place: ^0.4.7   ### Package Desativad, ver depois o que substituir
  google_places: 
    git:
      url: https://github.com/caneto/google_place.git 

  geocoding: ^2.1.1
  geolocator: ^9.0.2

  #FaceBook
  flutter_facebook_auth: ^5.0.11

  cupertino_icons: ^1.0.6

dependency_overrides:
  http: ">=1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.3
  mobx_codegen: ^2.4.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf