name: cuidapet_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  asuka: ^2.0.2
  flutter_modular: ^5.0.3
  flutter_mobx: ^2.0.6+5
  mobx: ^2.1.4
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter_typeahead: ^4.3.6
  validatorless: ^1.2.3
  json_annotation: ^4.8.0
  flutter_screenutil: ^5.6.0
  sqflite: ^2.2.4+1
  synchronized: ^3.0.1
  # Fixado na versão 1.8.2 por conta do flutter_test
  path: 1.8.2
  nil: ^1.1.1
  intl: ^0.17.0
  
  flutter_dotenv: ^5.0.2
  logger: ^1.2.2

  flutter_secure_storage: ^7.0.1
  shared_preferences: ^2.0.18
  
  ##Firebase
  firebase_core: ^2.7.0
  firebase_analytics: ^10.1.4
  firebase_auth: ^4.2.9
  firebase_remote_config: ^3.0.13
  firebase_messaging: ^14.2.5
  google_sign_in: ^6.0.1  
  google_maps_flutter: ^2.2.4
  google_place: ^0.4.7   ### Package Desativad, ver depois o que substituir

  geocoding: ^2.0.5
  geolocator: ^9.0.2

  #FaceBook
  flutter_facebook_auth: ^5.0.7

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.1
  mobx_codegen: ^2.1.1


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf