name: cuidapet_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  asuka: ^2.1.0
  flutter_modular: ^5.0.3
  flutter_mobx: ^2.0.6+5
  mobx: ^2.2.0
  dio: ^5.1.2
  equatable: ^2.0.5
  flutter_typeahead: ^4.6.1
  validatorless: ^1.2.3
  json_annotation: ^4.8.1
  flutter_screenutil: ^5.8.4
  sqflite: ^2.2.8
  synchronized: ^3.1.0
  # Fixado na versão 1.8.2 por conta do flutter_test
  path: ^1.8.3
  nil: ^1.1.1
  
  intl: ^0.18.1
  url_launcher: ^6.1.10

  flutter_dotenv: ^5.1.0
  logger: ^1.3.0


  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.1.1

    
  ##Firebase
  firebase_core: ^2.13.1
  firebase_analytics: ^10.4.2
  firebase_auth: ^4.6.2
  firebase_remote_config: ^4.2.2
  firebase_messaging: ^14.6.2
  google_sign_in: ^6.1.3  
  google_maps_flutter: ^2.2.8
  google_places: 
    git:
      url: https://github.com/caneto/google_place.git 
      
  #google_place: ^0.4.7     

  geocoding: ^2.1.0
  geolocator: ^9.0.2

  #FaceBook
  flutter_facebook_auth: ^5.0.7

  cupertino_icons: ^1.0.5

dependency_overrides:
  http: ">=1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  json_serializable: ^6.7.0
  flutter_lints: ^2.0.1
  mobx_codegen: ^2.3.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf